title: Grace Stonecipher # your name (or website title) here
logo: "/images/headshot_circle.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/gracestonecipher/">View My LinkedIn Profile</a> 
 

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: jekyll-theme-minimal

