title: Grace Stonecipher # your name (or website title) here
logo: "/images/headshot_circle.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Spatial Analysis, Data Visualization, Conservation
  <br><br>
  <a href="https://www.linkedin.com/in/gracestonecipher/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="mailto:grace.stonecipher@gmail.com">Email Me</a>
 
theme: jekyll-theme-minimal

